module.exports = {
  NO_USER: 'NO_USER',
  NO_PERMISSIONS: 'NO_PERMISSIONS',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_NOT_ACTIVE: 'USER_NOT_ACTIVE',
  NAME_REQUIRED: 'NAME_REQUIRED',
  EMAIL_REQUIRED: 'EMAIL_REQUIRED',
  PASSWORD_REQUIRED: 'PASSWORD_REQUIRED',
  WRONG_KEY: 'WRONG_KEY',
};
